### PR TITLE
[Circleci] Upgrade to Xcode 12.0.0

### PR DESCRIPTION
**Pull request by dogo**

### CODE REVIEW

**Comment by ashfurrow** [comment]
I fixed the bundler error in b634962, let's see what happens now...

**Comment by dogo** [comment]
> 
> 
> I fixed the bundler error in [b634962](https://github.com/ashfurrow/Nimble-Snapshots/commit/b634962962696e0111a2c1269d04bf36d23d34cc), let's see what happens now...

Nice catch!

**Comment by ashfurrow** [comment]
It succeeded! In the sense that it failed _differently_ 😅 Let me know if I can help with those failures too!

**Comment by dogo** [comment]
@ashfurrow, those 2 tests failing on the CI doesn't fail locally. Any thoughts?

**Comment by ashfurrow** [comment]
@dogo Hmm good question. The Artifacts tab on the Circle CI build has uploaded images for the failed tests (the reference image, the failed image, and a computed diff which isn't always reliable). When I downloaded one of the reference/failed image pairs and compared them, I only saw very slight differences:



Otherwise they look identical:

Screen Shot 2020-10-08 at 08 49 24

So  the failure is probably something to do with antialiasing. This can change between iOS and Xcode versions, so double-check that you're using the same simulator. We could also add a call to `setNimbleTolerance(0.1)` to allow for a ten percent allowance in pixel differences (and a comment explaining why it's there).

Let me know if I can help 👍

**Comment by dogo** [comment]
Yep! adjusting the tolerance seems to work! Nowww fails at Carthage step hehehe, we need an update from ios-snapshot-test-case to fix this

**Comment by dogo** [comment]
@ashfurrow seems to be a Carthage + Xcode issue. So I have added the suggested shell script to fix.
Reference: https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md

**Comment by dogo** [comment]
Now it's failing because of 

```❌  /Users/distiller/Nimble-Snapshots/Nimble_Snapshots/PrettySyntax.swift:48:27: argument 'file' must precede unnamed argument #1
    expect(snapshottable, file: file, line: line).to(recordSnapshot())
           ~~~~~~~~~~~~~~~^~~~~~~~~~
❌  /Users/distiller/Nimble-Snapshots/Nimble_Snapshots/PrettySyntax.swift:53:27: argument 'file' must precede unnamed argument #1
    expect(snapshottable, file: file, line: line).to(recordSnapshot(named: name))```

**Comment by ashfurrow** [comment]
Gotcha, so once the feedback on #209 is applied we can merge everything then?

**Comment by dogo** [comment]
> 
> 
> Gotcha, so once the feedback on #209 is applied we can merge everything then?

Yes :D

**Review by ashfurrow — APPROVED** [review]
I've pulled in the latest changes after merging #209. Let's see what CI says!

**Comment by ashfurrow** [comment]
Whaaaat? I don't get it. I'll try to take a look later. @dogo if you get this to be green, feel free to merge 👍

**Comment by dogo** [comment]
@ashfurrow All green! 🥳

**Pull request merged**
