### PR TITLE
Update ios-snapshot-test-case

### PR DESCRIPTION
**Pull request by dogo**
**MR Changes:**
Update ios-snapshot-test-case to 5.0.2
Fix compareSnapShot signature

**Motivation:**
Update the ios-snapshot-test-case library to a newer version without breaking compatibility with iOS 8.x or 9.x, since ios-snapshot-test-case 6.x supports only iOS 10.x or newer

### CODE REVIEW

**Comment by dogo** [comment]
@ashfurrowbot The PR became big because I had to run a pod install setting `pod 'iOSSnapshotTestCase', '~> 5.0'` , so most of changes are pod related

**Comment by ashfurrow** [comment]
@dogo can you pull the upstream changes and push to your branch? CI should be fixed now 👍

**Comment by ashfurrow** [comment]
Ah whatever, let's merge 👍

**Comment by ashfurrow** [comment]
Alright, I've released 6.9.1 so you should be good to go 👍

**Comment by dogo** [comment]
Thanks @ashfurrow

**Pull request merged**
