### PR TITLE
Migrate from FBSnapshotTestCase to iOSSnapshotTestCase

### PR DESCRIPTION
**Pull request by freak4pc**
Facebook have [archived FBSnapshotTestCase](https://github.com/facebookarchive/ios-snapshot-test-case) but have [reached an understanding with Uber](https://github.com/facebookarchive/ios-snapshot-test-case/pull/245) where they would be the new maintainer of the library. 

With this change that was officially published yesterday, the dependencies for this repo are changed.

### CODE REVIEW

**Comment by freak4pc** [comment]
Not sure why Circle isn't triggering - any thoughts? @ashfurrow

**Comment by ashfurrow** [comment]
Hmm, let me check.

**Comment by ashfurrow** [comment]
well there's the problem:

screen shot 2018-01-13 at 12 17 54 pm

Fixed that now, re-triggering.

**Comment by ashfurrow** [comment]
Can't wait for GitHub to deploy https://github.com/github/linguist/pull/3865

**Comment by ashfurrow** [comment]
Hmm, CI failed but it's not your PR's fault. One second.

**Comment by freak4pc** [comment]
@ashfurrow oh I hear ya ... should be soon enough though :)

**Comment by freak4pc** [comment]
@ashfurrow are-CI failure I had the same issue locally. Should we just target iPhone 6? Or actually ... that might cause the snapshot tests to fail

**Comment by ashfurrow** [comment]
I think the problem is (see #143) that Circle upgraded their images to only have iOS 11.0.1 (instead of 11.0). In the past, we've seen upgrades to iOS version cause antialiasing differences and snapshot test failures. I'm downloading the latest Xcode 9 (mine was still a beta lol) and I'll fix CI, then we can update your PR to get it green. Let me know what I can clarify.

**Comment by freak4pc** [comment]
@ashfurrow I just rebased on top of master (seemed easier)

**Comment by freak4pc** [comment]
Looks good to merge and you can also close #144 along the way

**Comment by freak4pc** [comment]
I think you merged the wrong PR but no biggie :)

**Comment by ashfurrow** [comment]
Oh, sorry just saw this! I merged #144 but hey. Thanks again for the PR!

**Comment by freak4pc** [comment]
Sure thing !

**Comment by ashfurrow** [comment]
I pulled in your exact commits, so they'll be in the git history :smile: Sorry for suddenly stopping, too, my computer died and wouldn't turn back on for a while 😕

**Comment by freak4pc** [comment]
That’s totally OK, really appreciate your help :)

**Pull request closed without merging**
