### PR TITLE
Add Swift Package Manager support

### PR DESCRIPTION
**Pull request by dogo**
Hi @ashfurrow could you please test this PR ? My MacBook is too old to run Big Sur (MacBook 2013), so I'm stuck with Catalina and Xcode 12.3

### CODE REVIEW

**Comment by dogo** [comment]
> contains mixed language source files; feature not supported

Humm, SPM supports mixed-language source files, but I have to split them into separated targets. Thanks .

**Comment by dogo** [comment]
@ashfurrow Could you please test again? 
I made the SPM  target split

**Review by ashfurrow — APPROVED** [review]
Cool! This worked on my machine 👍 

As I said, I'm not an SPM user, so I could use some help with the following:

- What instructions should we add to the README to help people use this with SPM?
- When we release a new version of `Nimble-Snapshots`, is it sufficient to create a git tag that matches the new version number? Or do we need to modify the `Package.swift` file like we do with the podspec?
- Could we add a changelog entry?

After that, we should be good to merge 🙌 Thanks again!!

**Comment by dogo** [comment]
@ashfurrow 

Answering your questions:
1) The instructions could be something like this: https://github.com/dogo/SketchKit#swift-package-manager-spm
2) SPM uses the repo tags, just this :D
3) I don't understand the question,

**Comment by ashfurrow** [comment]
Oh, I was asking if you could include an entry in this repository's [changelog](https://github.com/ashfurrow/Nimble-Snapshots/blob/master/CHANGELOG.md). But I can add it and the readme change tomorrow 👍

**Comment by dogo** [comment]
Owww! my bad! heheheh! Changelog updated

**Pull request merged**
