### PR TITLE
Add support for Carthage

### PR DESCRIPTION
**Pull request by Lascorbe**
Hi 😊

First, thank you for your continuos support and work on the OSS community 🍻 

So, just if you're interested in adding support for Carthage, this PR adds it.
I know that accepting this, it might add to this project the need to keep the support for that dependency manager in the future, so up to you 😃 

On other news, this goes with the `Quick v0.9.3` and `Nimble v4.1.x` versions that support Swift 2.3. To support Swift 3, as you may know, we should change the versions to use `Quick v1.x` and `Nimble v5.x`.

¡Ya tu sabes! 🍷 

cc @juolgon

### CODE REVIEW

**Comment by ashfurrow** [comment]
Why the close? Was going to merge this.

**Comment by Lascorbe** [comment]
Hey @ashfurrow, sorry, I want to make sure everything is in place, the Travis CI passes, and I add the Carthage step on the CHANGELOG. I closed it so you didn't lose the time before I get that done, sorry about the confusion.

**Comment by ashfurrow** [comment]
Cool cool, just re-open when you're ready 👍

**Comment by Lascorbe** [comment]
I think now it's ready 😃 

Ok so, I couldn't think of a way of having both Swift versions (2.3 and 3.0) working with Carthage, so I had to release 2 versions to make clear which one supports which version:
- Nimble-Snapshots `v4.4.1` -> `Swift 2.3`
- Nimble-Snapshots `v4.4.2` -> `Swift 3.0`

**Comment by ashfurrow** [comment]
Super-awesome, thanks!

**Pull request merged**
