### PR TITLE
Swift 2 updates

### PR DESCRIPTION
**Pull request by tibr**
This pull request updates the code for the latest Swift 2 (Xcode 7.0 beta 5).

It also updates Quick and Nimble to the latest versions.

### CODE REVIEW

**Comment by orta** [comment]
This looks :+1:  to me

**Comment by orta** [comment]
We should bump this to `1.0.0` when pushing the podspec

**Comment by ashfurrow** [comment]
Cool, should we wait for Swift 2's public release you think?

**Comment by tibr** [comment]
I think that you could release `1.0.0` already because `0.x` users won't be updated automatically. And that's what a lot of other frameworks are doing as well.

**Comment by orta** [comment]
Yeah, I'm with @tibr :+1:

**Comment by ashfurrow** [comment]
Cool, this looks great! I'm going to merge and push a `1.0.0`.

**Comment by ashfurrow** [comment]
Cool, that's up! https://raw.githubusercontent.com/CocoaPods/Specs/486f111eb038e3914ec9130b502868190718b5aa/Specs/Nimble-Snapshots/1.0.0/Nimble-Snapshots.podspec.json

**Pull request merged**
