### PR TITLE
Support Nimble v11

### PR DESCRIPTION
**Pull request by younata**
Which is out now, and breaks this API.

### CODE REVIEW

**Review by ashfurrow — APPROVED** [review]
Looks good, thanks! Let me know when this is good to merge 👍

**Comment by younata** [comment]
Hey @ashfurrow! I released Nimble V11 today, this PR should be good to merge now. Thanks!

**Comment by ashfurrow** [comment]
Great, thanks! I’ll try to get this release today/this week.

**Comment by ashfurrow** [comment]
Thanks for your patience – I've released this as `9.5.0`. Future releases should be faster – I had to install the tvOS dev kit just to get `pod trunk push` to work 😅

**Pull request merged**
