### PR TITLE
Added optional tolerance parameter for comparing snapshots with FBSnapshotTestCase

### PR DESCRIPTION
**Pull request by mpurland**

### CODE REVIEW

**Comment by ashfurrow** [comment]
Cool, looks awesome! I'll merge shortly, gonna try and add a few tests and a changelog entry.

**Comment by ashfurrow** [comment]
Did that in https://github.com/ashfurrow/Nimble-Snapshots/commit/513e710714c242f60ed04723e5e014d8d818a850

@mpurland I've sent an invitation to add you as a collaborator to this repo, no pressure! It's nice to have a helping hand in case @orta or I aren't around to help review issues and PRs, and if you're interested we'd love your assistance :bow:

**Comment by mpurland** [comment]
@ashfurrow Thanks. I'd be happy to help out.

**Comment by tbondwilkinson** [comment]
@ashfurrow or @mpurland can you update the podspec and push the pod for this change?  Would be awesome to use this!

**Comment by ashfurrow** [comment]
Pushing now, if there are no issues then it should be done soon.

**Comment by ashfurrow** [comment]
Should be up now: https://raw.githubusercontent.com/CocoaPods/Specs/aa4828d3773e5dfb7d6d687ce1befc7d88517dab/Specs/Nimble-Snapshots/4.1.0/Nimble-Snapshots.podspec.json

**Pull request merged**
