### PR TITLE
Upgrade for Swift 5.0 and Xcode 10.2.1

### LINKED ISSUE #185: Xcode 10.2 / swift 5 Compatability
pretty please :)

### PR DESCRIPTION
**Pull request by Vkt0r**
Hey guys, long time! 😅. 

This PR brings support for Swift 5.0 and Xcode 10.2.1 and can be resumed in the following:

* Upgrade the library to the recommended settings in Xcode 10.2.1
* Upgrade the `ios-snapshot-test-case` library to 6.0.3 
* Update the **Bootstrap** project to Swift 5.0
* Add a new step in `circle.config` to test for Swift 5.0 and update the Xcode version to 10.2.1
* Update the tests for agnostic devices for iOS 12.2 and deleted the old ones
* Drop the Swift 4.0 tests in CircleCI regarding issues of incompatibility in Nimble.

Resolves #185.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Okay! That should be released. Let me know if you have any issues – and thanks again!

**Comment by Lascorbe** [comment]
@ashfurrow was this released on `7.0.0`/`7.1.0`?

**Comment by Lascorbe** [comment]
I just say the commits being included, I've updated the release notes accordingly 👍 thanks!!

**Comment by ashfurrow** [comment]
@Lascorbe great, thanks!

**Pull request merged**
