### PR TITLE
- Fixes https://github.com/ashfurrow/Nimble-Snapshots/issues/258

### PR DESCRIPTION
**Pull request by anton-plebanovich**
Fixes https://github.com/ashfurrow/Nimble-Snapshots/issues/258

### CODE REVIEW

**Review by ashfurrow — APPROVED** [review]
Thank you! Makes sense based on [these docs](https://xcodebuildsettings.com/#enable_testing_search_paths). Lets merge now and I’ll release when I can 👍

**Comment by ashfurrow** [comment]
Looks like the CI failure is unrelated to your change. Let’s merge 👍

**Comment by ashfurrow** [comment]
I've got this released in version 9.6.1 – thank you again!

**Comment by anton-plebanovich** [comment]
Thank you for maintaining the framework 👍

**Pull request merged**
