### PR TITLE
Adds ability to use device model and OS on image names

### PR DESCRIPTION
**Pull request by esttorhe**
From facebook/ios-snapshot-test-case#121:
>We like to actually record snapshots on multiple devices and multiple `OS`s (using bots for example is easier to automate testing on `iPad`/`iPhone` and a combination of different `OS`s).
>
>Instead of having to manually pass the data to each test I added a new property:
`recordModelAndOSInName` which is used to check if those elements should be added to the recorded/retrieved image later on the comparison; resulting on an image name like the following:
>
>> context_controller_being_tested_iPhone9_0.png
>
>Probably the names of the functions & properties could use some imagination but the functionality is there.

Following the same lines; after adding support for the `model` and `OS` I came here and added support for the `Nimble` matchers.

Same as the other `PR` names could use some imagination and I was not able to figure out an easy way to support the `==` with the `model` and `OS` :disappointed:

### CODE REVIEW

**Comment by orta** [comment]
Perhaps "device agnostic" is a good term for this, making it `haveValidDeviceAgnosticSnapshot` and `recordDeviceAgnosticSnapshot` - regardless of the underlying argument name?

**Comment by esttorhe** [comment]
:+1: i knew I needed some help with naming things.

I'll update the names here and on facebook/ios-snapshot-test-case#21 and will come back here for a review.

**Comment by esttorhe** [comment]
Definitely looks better now :bow:

**Comment by esttorhe** [comment]
FYI facebook/ios-snapshot-test-case#121 was merged like a week or so ago and there's a pod out there that already includes this (`2.0.5`)

Just saying in case that was the issue preventing this from being merged; if that was not it let me know what I should change to make it go.

Thanks

**Comment by ashfurrow** [comment]
Neat! I'll take another look this weekend. Thanks Esteban!

**Comment by ashfurrow** [comment]
@orta: thoughts on how we could incorporate this work with our solution in eigen?

**Comment by esttorhe** [comment]
Nah; thank you for porting the snapshot matchers to `Nimble`.

And thanks for looking at this :bow:

**Comment by orta** [comment]
This is in Nimble, which eigen/energy don't use, it's free to have all the additions in the world. 

@esttorhe I'd like to see the Podfile go back to production, and the Podspec's reference to FBSnapshot be classed as the last release or higher, so that support is definitely in.

I figure this repo is just totally red, Xcode doesn't even boot. So that doesn't look like the fault of this PR. Good old, working with black box tools. Looks mergable to me :+1:

**Comment by esttorhe** [comment]
@orta done; changed the dependency on the `.podspec` to support `2.0.5` or above.

Also fixed some failing tests due to the change on the naming convention. Related to this I don't think the tests are being «locked» to a specific device and thus; the `deviceAgnostic` names might fail because I recorded them on a `iPad Air 2` simulator running `8.0`

**Comment by orta** [comment]
This makes sense, at some point we should audit the issues and make this repo green, until then :+1:

**Comment by ashfurrow** [comment]
Awesome, good idea. Thank for getting to this Orta. I've opened #33 to follow up. Thanks again Esteban!

**Pull request merged**
