### PR TITLE
Make it possible to use it without Quick

### LINKED ISSUE #51: Without Quick
Could this also work without Quick? We are using Nimble in our project but not Quick.

### PR DESCRIPTION
**Pull request by marcelofabri**
Will partially fix #51. Quick will still be needed as a dependency for now, but now the matchers can be used inside a regular `XCTestCase`.

~This won't work well if the user mixes `XCTestCase` and Quick suites, but ¯\_(ツ)_/¯~

**TODO:**

- [x] ~Add the new `file` parameter to all matchers~ Fixed by using `actualExpression` from Nimble
- [x] ~Support Swift 2.3~
- [x] Handle the test name -> image name better (avoiding `_` in the beginning/end)

### CODE REVIEW

**Comment by ashfurrow** [comment]
Interesting, cool!

**Comment by marcelofabri** [comment]
@ashfurrow Can I open a PR getting rid of Swift 2.3 so I don't actually need to support it on this new PR?

**Comment by ashfurrow** [comment]
Sounds like a plan :100:

**Comment by marcelofabri** [comment]
This is ready for review 🚀

**Comment by ashfurrow** [comment]
Probably add a changelog entry? Then we're good to merge, thanks for all your hard work!

**Comment by orta** [comment]
👍

**Comment by coverback** [comment]
@marcelofabri or @ashfurrow Could you tell in short what remains to be done to make Quick entirely optional? Maybe I'd have a go at that.

I'm also using Nimble with XCTest.
Thanks for the library!

**Comment by marcelofabri** [comment]
One possible approach would be trying to get rid of it totally, since we only use it to get the current test name: https://github.com/ashfurrow/Nimble-Snapshots/blob/master/HaveValidSnapshot.swift#L198-L200

This however, could involve manipulating the test name (from `XCTest`) to be equal to the one from `Quick` (to keep compatibility).


Another approach would be making a subspec and trying to use dynamic checks, but I wouldn't go with this approach since we already have 2 subspecs => we'd need 6 in total.

**Comment by coverback** [comment]
@marcelofabri Thanks for the reply!

There's also an option to go dynamic without dependency in the podfile (through checking if Quick's there and using `performs selector`). Is that out of the question?

In terms of compatibility, would it make sense to copy the naming implementation into the project, and not update it in case Quick updates theirs? Or do we need forward-compatibility as well, to always have the same name as Quick, as long as Quick is used?

**Comment by marcelofabri** [comment]
> There's also an option to go dynamic without dependency in the podfile (through checking if Quick's there and using performs selector).

That could be an option too, but I think we'd need a major release since it'd be a breaking change

> In terms of compatibility, would it make sense to copy the naming implementation into the project, and not update it in case Quick updates theirs? 

I think this would be fine (if not preferred). It would be bad if Quick changed it and all the snapshots tests failed 😲. Maybe @ashfurrow has some thoughts here as well.

**Comment by ashfurrow** [comment]
I'm okay without forward compatibility, since we can always update later. I'm also okay with a breaking change – we can just release a new major version. As always, just let me know what I can do to help 👍

**Pull request merged**
