### PR TITLE
Fix Swift Package definition

### PR DESCRIPTION
**Pull request by diogot**
The update to Nimble 11 something had broking in the Package configuration, I fixed it and also update to new syntax to avoid deprecation warnings.

### CODE REVIEW

**Review by ashfurrow — APPROVED** [review]
Thanks! I don’t use Swift day-to-day anymore so I appreciate this pull request. Swift had never made any syntax it doesn’t want to change later, eh? 😂😭

**Comment by diogot** [comment]
Don't worry, I use Swift daily but never write package descriptions too, hehe.
Did I messed up something that make Danger fail?

**Comment by ashfurrow** [comment]
Nah it's probably unrelated – probably a permission thing running from a fork. Merging 👍

**Comment by ashfurrow** [comment]
Okay! So tests are failing, but they're failing on `master` too 😬😅  I've opened #257 to investigate. In the meantime, I'm going to merge. Let me know if we should release a new version of the library.

**Comment by diogot** [comment]
Hi, sorry for the delay, too many things happening.
I checked and we need a new release.

**Comment by diogot** [comment]
Is this (create a new release) something that I can do?

**Comment by ashfurrow** [comment]
Unfortunately, I need to do it because releasing involves both pushing a tag to GitHub and a CocoaPods podspec. I know this is an SPM-only change but I want to keep them in lockstep.

I've pushed up this change in version 9.5.1 and the podspec is pushing now. You should be good to go, let me know 👍 Thanks for your patience on this – I've had a death in the family recently and open source hasn't been a priority for me.

**Comment by diogot** [comment]
I'm sorry for you loss 😔

Regarding the release everything is working great, and thank you very much for been so helpful!

**Pull request merged**
