### PR TITLE
Fix support to XCTest when using Carthage

### PR DESCRIPTION
**Pull request by marcelofabri**
Fix https://github.com/ashfurrow/Nimble-Snapshots/pull/93#issuecomment-301403640

### CODE REVIEW

**Comment by orta** [comment]
Sure, seems legit enough

**Comment by marcelofabri** [comment]
Can we have a new release? 

Giphy

**Comment by orta** [comment]
I'll leave that to @ashfurrow

**Comment by ashfurrow** [comment]
Yup, will do today. 5.0.1 sounds right?

**Comment by marcelofabri** [comment]
> Yup, will do today. 5.0.1 sounds right?

💯

**Comment by ashfurrow** [comment]
Okay, I've tagged+pushed, and pushed to CocoaPods for the sake of consistency. Let me know if it works :bow:

**Pull request merged**
