### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by ashfurrow**
Merges #31.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Two commits: https://github.com/ashfurrow/Nimble-Snapshots/commit/6d9b3c2e767f84f4f192581a2882c98fc4f282fc merges from master, and https://github.com/ashfurrow/Nimble-Snapshots/commit/e5f34d55918685437b51b2611972e074f20ff28f makes some changes for code style. 

Also, I had to rename one of the images. It had a space in the file name, which should not have been there. Must've been a bug fixed with @colinta 's changes? Not sure. @esttorhe could you take a look at this PR? Is the filename change a breaking change? If so, we'll need to release a 2.0 after this.

**Comment by esttorhe** [comment]
Finishing some last minute Halloween decorations. Will test in a few 

--
Esteban Torres
(+506)8813-0934
Twitter: @esttorhe




On Thu, Oct 29, 2015 at 8:51 PM -0700, "Ash Furrow" <notifications@github.com> wrote:












Two commits: 6d9b3c2 merges from master, and e5f34d5 makes some changes for code style. 



Also, I had to rename one of the images. It had a space in the file name, which should not have been there. Must've been a bug fixed with @colinta 's changes? Not sure. @esttorhe could you take a look at this PR? Is the filename change a breaking change? If so, we'll need to release a 2.0 after this.

**Comment by esttorhe** [comment]
Just finished this 🎃Will check tomorrow morning because I'm super tired right now 


--
Esteban Torres
(+506)8813-0934
Twitter: @esttorhe




On Thu, Oct 29, 2015 at 8:51 PM -0700, "Ash Furrow" <notifications@github.com> wrote:












Two commits: 6d9b3c2 merges from master, and e5f34d5 makes some changes for code style. 



Also, I had to rename one of the images. It had a space in the file name, which should not have been there. Must've been a bug fixed with @colinta 's changes? Not sure. @esttorhe could you take a look at this PR? Is the filename change a breaking change? If so, we'll need to release a 2.0 after this.

**Comment by ashfurrow** [comment]
Pffft don't worry about it!

**Comment by orta** [comment]
Let's also try get a test to cover whatever changed too :+1:

**Comment by ashfurrow** [comment]
That's tough – #31 lets developers' tests directory end in "specs" instead of "tests", so we'd have to test `FBSnapshotTest.setReferenceImagesDirectory` somehow. Suggestions?

**Comment by esttorhe** [comment]
@ashfurrow can confirm that the name change is not a breaking change :sweat_smile: 

no idea how that name got there or why it wasn't failing before but all the projects where i'm using this have the file names correctly sanitized.

I'll think of a way to test `FBSnapshotTest.setReferenceImagesDirectory` during the day

**Comment by ashfurrow** [comment]
Yeah, me too. There must've been some edge case that got inadvertently fixed. That's fine – we'll release 2.0 to adhere to semantic versioning :cake:

**Comment by esttorhe** [comment]
Do any of you know if there's a way in `Nimble` or `Quick` to «catch» a `fatalError` ?

First thing that came to my mind to test this was add the following test:

```swift
         it("fails when using an invalid images directory") {
            setNimbleTestFolder("invalid_folder")
            expect {
              expect(view).to(haveValidSnapshot())
            }.to(raiseException())
          }
```

Unfortunately `fatalError` does not count as an `exception` and is not being caught :/

**Comment by colinta** [comment]
No catching fatal errors, but if we marked this method as `throws` then we could use `do/catch/try` to do this test.

**Comment by esttorhe** [comment]
The problem i see with marking it as `throws` is that it will «clutter» end calls having to use `try` or worst `try!`.

I think the current `fatalError` is the expected behavior; just trying to find a way to test

**Comment by colinta** [comment]
Yeah I agree; annoying to have `try` everywhere.  It would be possible, but *also* annoying, to use a singleton "error emitter", and have it record the error while running specs.

```diff
- fatalError("...")
+ ErrorEmit.error("...")  // either fatalError, or just log the error.
+ return
```

**Comment by ashfurrow** [comment]
Tbh this seems like a config issue. Important to test, but not critical. And given that it's non-obvious how we could even do this, I'm leaning towards merging without testing that functionality. We should open an issue to revisit it though.

**Comment by colinta** [comment]
:+1: Seems like `fatalError` is enough to get people on the right path.

**Comment by esttorhe** [comment]
Its weird; don't know if I'm not understanding this but I created this structure:
screen shot 2015-10-30 at 3 39 59 p m

Then I'm testing this:
```swift
            var view: UIView!
            setNimbleTestFolder("CustomFolder")

            beforeEach {
                view = UIView(frame: CGRect(origin: CGPointZero, size: CGSize(width: 44, height: 44)))
                view.backgroundColor = UIColor.blueColor()
            }

            it("has a valid snapshot") {
                expect(view).notTo(haveValidSnapshot())
                expect(view).notTo(haveValidSnapshot(named: "something custom"))
            }
```

And even though the `testFolderSuffixes` is composed solely of `["CustomFolder"]` I'm getting the `fatalError` :/

Probably I'm not understanding this :100:

**Comment by colinta** [comment]
Xcode is a total liar on folder-vs-group structure.  Can you snapshot Finder?

**Comment by ashfurrow** [comment]
Your path _does_ contain a folder with the suffix "Tests", so it works as expected.

**Comment by esttorhe** [comment]
But I'm setting the suffix to "CustomFolder" so it should work shouldn't it?

**Comment by esttorhe** [comment]
@colinta like I wrote; my file structure matches Xcode's; I create them in `Finder` first then add them to the project or run `synx` on all my projects.

**Comment by colinta** [comment]
Oops!  Sorry, didn't see that... (it felt like an obvious thing - I'm looking at the code again)

**Comment by ashfurrow** [comment]
No, but this illustrates something missing from the PR – documentation. `setNimbleTestFolder()` replaces the folder completely. If it's not set, then we try to guess where you would want the images. So we grab the path of the unit test file and look through its path components. A file in `/Users/ash/App/AppTests/ViewControllers/ViewControllerTests.swift` will have the following:

- Users
- ash
- App
- AppTests
- ViewControllers

So the code looks through each of those, in order until it finds one that ends in "Tests" or "Specs" – then it appends `ReferenceImages` to the end, and puts the reference images in there: `/Users/ash/App/AppTests/ReferenceImages/`. Does that make sense? I can document that.

**Comment by esttorhe** [comment]
hehe; no need to apologize I did edit it after first sending it and you probably missed it

**Comment by colinta** [comment]
Sneaky!  Yeah I've keeping up via email. :smile:

**Comment by esttorhe** [comment]
Mmm; this is more confusing then because the implementation replaces the suffixes not the folders

```swift
public func setNimbleTestFolder(testFolder: String) {
    testFolderSuffixes = [testFolder]
}
```

**Comment by ashfurrow** [comment]
Ah, now I'm confused :confused:

**Comment by colinta** [comment]
*colin is typing* :smiley:

**Comment by colinta** [comment]
The method `_getDefaultReferenceDirectory` is written to accept the *first* tested file (not necessarily one with snapshot specs), and use it to find the "root" test/specs folder.  In your case, the folder it should find is `BootstrapTests`.

The `setNimbleTestFolder` is meant to be used if the user decided to use something silly, like `BootstrapTesting`.

**Comment by colinta** [comment]
In this case, the person could use `setNimbleTestFolder` either of these ways:

```
setNimbleTestFolder("Testing")
// or more intuitively
setNimbleTestFolder("BootstrapTesting")
```

**Comment by colinta** [comment]
and yes, documentation is lacking on this feature! :-(

**Comment by ashfurrow** [comment]
Gotcha! Give me two seconds.

**Comment by esttorhe** [comment]
ISP support ATM. 
But without info I would say change the name of that function. 

--
Esteban Torres
(+506)8813-0934
Twitter: @esttorhe




On Fri, Oct 30, 2015 at 2:51 PM -0700, "Colin T.A. Gray" <notifications@github.com> wrote:












colin is typing

**Comment by ashfurrow** [comment]
Nah, it works for me. The prefix thing isn't a deal-breaker – I kind of like it. Let me know what you think of those two commits ^

**Comment by ashfurrow** [comment]
Typo, force-pushed.

**Comment by colinta** [comment]
To @esttorhe's point, I think the use of suffixes is an implementation detail.  I think `setNimbleTestFolder` is a sensible name, even though what it *does* is check for a suffix.  If someone sets it to something weird, e.g. `setNimbleTestFolder("t")`, they'll run into trouble.

Edge case, though, what if the username is `abcdspecs`?  :-|

**Comment by ashfurrow** [comment]
@colinta Agreed – implementation detail. 

When that happens, I'm sure abcdspecs will open an issue :wink:

**Comment by esttorhe** [comment]
Can't comment much atm. Connected via a really crappy 3G. 
Will follow up the changes and comments in a few 😁

--
Esteban Torres
(+506)8813-0934
Twitter: @esttorhe




On Fri, Oct 30, 2015 at 3:03 PM -0700, "Colin T.A. Gray" <notifications@github.com> wrote:












To @esttorhe's point, I think the use of suffixes is an implementation detail.  I think setNimbleTestFolder is a sensible name, even though what it does is check for a suffix.  If someone sets it to something weird, e.g. setNimbleTestFolder("t"), they'll run into trouble.



Edge case, though, what if the username is abcdspecs?  :-|

**Comment by ashfurrow** [comment]
Take your time! No rush on this :cake:

**Comment by colinta** [comment]
haha! :+1: I'm ok with that logic.

`/Users/abcdspecs/Tests/CodeSpecs/Project/ProjectTests/`

^ you, sir or madam, are hosed.

**Comment by colinta** [comment]
Actually, `setNimbleTestFolder("ProjectTests")` would totally solve that.

:100:

**Comment by esttorhe** [comment]
Ok; I hacked some tests but i'm not :100: they make sense TBH :/

Let me upload to a different branch so you guys can review

**Comment by esttorhe** [comment]
Here they are FWIW:

https://github.com/esttorhe/Nimble-Snapshots/tree/esteban/mergeTests

**Comment by colinta** [comment]
*colin is typing*

**Comment by colinta** [comment]
@esttorhe I think the success is kind of a red-herring - the second call to `setNimbleTestFolder` (setNimbleTestFolder("tests")`) is *overriding* the first one (`setNimbleTestFolder("CustomFolder")`.  I think this is the case because the way the code is written, that image is *in the wrong place*.  The `ReferenceImages` folder should be relative to the folder that is discovered by `_getDefaultReferenceDirectory`, and so if `CustomFolder` were being discovered, the image location should be `/Users/esttorhe/.../Bootstrap/BootstrapTests/ACustomFolder/ReferenceImages`.

If `setNimbleTestFolder` is moved to inside `beforeEach`, I think you'll get a failure, which is good actually - in that case:

```
mv Nimble-Snapshots/Bootstrap/BootstrapTests/ReferenceImages/BootstrapCustomFolderTests/in_some_context__fails_to_find_the_snapshots_due_to_the_custom_folder@2x.png \
   Nimble-Snapshots/Bootstrap/BootstrapTests/ACustomFolder/ReferenceImages/BootstrapCustomFolderTests/in_some_context__fails_to_find_the_snapshots_due_to_the_custom_folder@2x.png
```

(I think)

**Comment by esttorhe** [comment]
Yup; the problem is that due to the way the tests are sorted; the `custom` could run before the «regular» one; which then tries to find the images under `customfolder` hence me setting it to `tests`

¯\\\_(ツ)\_/¯

I think we are good for now; this whole discussion lead to discovering a lot of issues and we should just merge, release and create a ticket to revisit this tests unless @orta or @ashfurrow have a better idea on how to test this :/

**Comment by colinta** [comment]
Yeah true... gimme just a few minutes to see if my idea is correct - otherwise I'll leave it be :-)

I'm pulling your branch to try it out.

**Comment by colinta** [comment]
Er, your fork I mean.

**Comment by colinta** [comment]
Actually, I think this works!

<https://github.com/esttorhe/Nimble-Snapshots/compare/esteban/mergeTests...colinta:esteban/mergeTests>

**Comment by esttorhe** [comment]
sadly is the same thing though; we are «overriding» de default behavior of the suffixes; all the tests are actually working with «custom» folders

**Comment by colinta** [comment]
How can they be the same?  The images are now in two totally different folder:

```
ReferenceImages/
└── BootstrapTests
    ├── in_some_context__has_a_valid_pretty_snytax_snapshot_without_specifying_a_name@2x.png
    ├── in_some_context__has_a_valid_snapshot@2x.png
    ├── in_some_context__has_a_valid_snapshot_with_model_and_OS_in_name_iPad9_0@2x.png
    ├── in_some_context__has_a_valid_snapshot_with_model_and_OS_in_name_iPad9_1_768x1024@2x.png
    ├── something_custom@2x.png
    └── something_custom_with_model_and_OS_iPad9_1_768x1024@2x.png
ACustomFolder/ReferenceImages/
└── BootstrapCustomFolderTests
    ├── in_some_context__fails_to_find_the_snapshots_due_to_the_custom_folder@2x.png
    ├── in_some_context__finds_device_agnostic_snapshots_with_custom_images_directory_iPad9_1_768x1024@2x.png
    └── in_some_context__finds_the_snapshots_using_a_custom_images_directory@2x.png
```

**Comment by esttorhe** [comment]
Yeah; not that. I actually merged your `pr` in regards of the locations.

I think this is good enough but I wish there was a way to either guarantee the order of the tests or to reset the suffixes

**Comment by colinta** [comment]
Ahh I think I see what you're saying.  Calling `setNimbleTestFolder` even *once* is enough to set it to a custom value.

The closest we could get, if I'm understanding you correctly, is

```swift
beforeEach {
  setNimbleTestFolder("CustomFolder")
}
afterEach {
  setNimbleTestFolder("tests") // a "reset", but not really a reset.  good enough for specs, though!
}
```

**Comment by colinta** [comment]
I'm happy just to see it tested, though - can we merge <https://github.com/esttorhe/Nimble-Snapshots/tree/esteban/mergeTests> into this PR?

**Comment by esttorhe** [comment]
yeah; although for specs sake i think this is good enough; i'm going to merge my branch into this one merge back to master then create an issue to revisit this tests.

BTW. The location of the images was what i was looking for; thanks for fixing it :)

**Comment by esttorhe** [comment]
> @colinta: I'm happy just to see it tested, though - can we merge https://github.com/esttorhe/Nimble-Snapshots/tree/esteban/mergeTests into this PR?

Yup; give me a sec

**Comment by colinta** [comment]
:100: :rainbow:

**Comment by esttorhe** [comment]
OK; tests are :green_apple: 

@ashfurrow you :100: with me merging this into `master` and release `2.0.0`?

**Comment by ashfurrow** [comment]
I am, I am 100% :100:

**Comment by esttorhe** [comment]
This was merged via `git am` to avoid «noise» on the commits

First commit is a3ccd5c566f73da238f6327ef24626b14676a621
And last one is e7bc7aa50226f93ebff32db6ec08037be87098f9

I'm going to push a new version to trunk right now

**Comment by esttorhe** [comment]
Thanks a lot @colinta :ok_hand:

**Pull request closed without merging**
