### PR TITLE
Add support for views that responds to traitCollectionDidChange:

### PR DESCRIPTION
**Pull request by marcelofabri**
😈 

(I'm open for less hacky ways to do this)

### CODE REVIEW

**Comment by marcelofabri** [comment]
This doesn't seem to propagate to subviews (and potentially child view controllers) 😭

**Comment by marcelofabri** [comment]
🚂

**Comment by yas375** [comment]
@marcelofabri thanks for handling trait collections too! :+1: I had the exact issue and was going to share my [workaround](https://gist.github.com/yas375/c11aaf3bac377905d1401d060801b473), which is probably too late now. I basically have added an observer for `UIContentSizeCategoryDidChange` and was calling `traitCollectionDidChange` on the view controller from there. Anyway, I'm glad I won't need it anymore :)

**Comment by marcelofabri** [comment]
@yas375 can you give it a try just to be sure that this PR fits your use case as well? 🙏

**Comment by yas375** [comment]
@marcelofabri will definitely do! Probably won't make it today and I'm out tomorrow. Will do on Wednesday then.

**Comment by marcelofabri** [comment]
no worries :)

**Comment by yas375** [comment]
@marcelofabri sorry for the delay on my side. Finally I removed my wrapper and your solution works. Just one note:

If I do just:

```swift
let storyboard = UIStoryboard(name: "Foo", bundle: nil)
let controller = storyboard.instantiateViewController(withIdentifier: "Bar")
expect(controller).to(haveValidDynamicTypeSnapshot())
```

The call to `haveValidDynamicTypeSnapshot` triggers [`traitCollectionDidChange` call](https://github.com/ashfurrow/Nimble-Snapshots/blob/89a32c4c25414aa79c79030a61f4f6c3bdc18add/DynamicType/HaveValidDynamicTypeSnapshot.swift#L104), but the view is not loaded yet. In our implementation for dynamic type support we actually update our custom font in `UIViewController#traitCollectionDidChange` and because the view is not loaded at this point, it crashes when trying to access a label which wasn't loaded from storyboard yet.

 It works I trigger a view to be loaded first with:

```swift
controller.beginAppearanceTransition(true, animated: false)
controller.endAppearanceTransition()
```

But it probably would be nice if the library can do this for us similar to how [it does it in `HaveValidSnapshot`](https://github.com/ashfurrow/Nimble-Snapshots/blob/89a32c4c25414aa79c79030a61f4f6c3bdc18add/HaveValidSnapshot.swift#L11-L17).

---

I wanted to submit a PR with the fix, but couldn't find an agreement with myself how to fix this nicely. Here are a few options to consider if you are going to address this issue.


## Option 1

```diff
diff --git a/DynamicType/HaveValidDynamicTypeSnapshot.swift b/DynamicType/HaveValidDynamicTypeSnapshot.swift
index f428604..75f214a 100644
--- a/DynamicType/HaveValidDynamicTypeSnapshot.swift
+++ b/DynamicType/HaveValidDynamicTypeSnapshot.swift
@@ -100,6 +100,7 @@ private func updateTraitCollection(on expression: Expression<Snapshotable>) {
 }

 private func updateTraitCollection(on element: Snapshotable) {
+    _ = element.snapshotObject // will trigger a view to be loaded in case we are dealing with UIViewController
     if let environment = element as? UITraitEnvironment {
         environment.traitCollectionDidChange(nil)
```

## Option 2

```diff
diff --git a/DynamicType/HaveValidDynamicTypeSnapshot.swift b/DynamicType/HaveValidDynamicTypeSnapshot.swift
index f428604..2f83f31 100644
--- a/DynamicType/HaveValidDynamicTypeSnapshot.swift
+++ b/DynamicType/HaveValidDynamicTypeSnapshot.swift
@@ -101,6 +101,11 @@ private func updateTraitCollection(on expression: Expression<Snapshotable>) {

 private func updateTraitCollection(on element: Snapshotable) {
     if let environment = element as? UITraitEnvironment {
+        if let vc = environment as? UIViewController {
+            vc.beginAppearanceTransition(true, animated: false)
+            vc.endAppearanceTransition()
+        }
+
         environment.traitCollectionDidChange(nil)

         if let view = environment as? UIView {
```

I personally lean towards second option even though it's a couple more LOC. More explicit.

But maybe you'll have a 3rd option :)

**Comment by marcelofabri** [comment]
@yas375 thanks for the detailed description 🎉 

When I implemented this, I was focusing on `UIView`s (because that was what I needed), so I didn't catch this issue.

I also slightly prefer #2, but feel free to pick the one you prefer. I'd be awesome if you could also add a test for this, creating a view controller from a nib/storyboard and implementing `traitCollectionDidChange`.

Thanks again!

**Pull request merged**
