### PR TITLE
Fix an error regarding iOSSnapshotTestCase breaking change in v4.0.0

### PR DESCRIPTION
**Pull request by Vkt0r**
Hi guys,

This PR address a breaking change in the last released version of `iOSSnapshotTestCase `.  Our last compatible version was `3.0.0`.  In the last versions, the initializer we were using to create the instance of `FBSnapshotTestController` changed to use the class name of the test class breaking our compatibility, see [this](https://github.com/uber/ios-snapshot-test-case/commit/0ab64921ebc37fe99fffac071cd9bbecd9ba5f1a#diff-0b01f7ec542c2ffa19cbde06671b867eL23).

They introduced a new variable called `folderName` to set folder name where snapshots are going to be saved for each test case. The change is really simple in the PR, just calling the new initializer with `self` as an instance and set the `folderName` property.

The PR can be resumed here:

• Fix an error regarding iOSSnapshotTestCase breaking change with a removed initializer.
• Update the dependencies in the Cartfile.
• Update the podspec file to increase the version of iOSSnapshotTestCase to 4.0.0.
• Update the Bootstrap project Podfile dependencies.

There are more coming changes in the library deprecating `deviceAgnostic ` in favor of `agnosticOptions` that I plan to address after this PR 😅.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Hey, this sounds cool! I'm unable to review it for a few days, but I'll take a look then, thanks!

**Comment by Vkt0r** [comment]
@ashfurrow No problem no rush 👍.

**Comment by Vkt0r** [comment]
@ashfurrow Sounds good, thanks

**Comment by ashfurrow** [comment]
Okay! Released as 6.8.0. Thanks again!

**Pull request merged**
