### PR TITLE
Xcode 9 beta 6 and Swift4 changes

### PR DESCRIPTION
**Pull request by danielsaidi**
This pr contains minor changes, that make the `master` branch build correctly in Xcode 9 beta 6. I have just made a global function public and removed an optional check that is no longer needed.

I tried the `xcode-beta` branch first, but it did not work in Xcode 9 beta 6.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Hi @danielsaidi! Thanks for the pull request, and thanks for trying the `xcode-beta` branch. @acrookston and @spekke: as our resident Xcode 9 experts, how does this pull request look to you two? We probably still want to hold off until Xcode 9 GM is released (next week?) but it's up for discussion.

**Comment by orta** [comment]
Great 👍

**Comment by marcelofabri** [comment]
We probably want to support Swift 3.2 and 4 for a while.

**Comment by danielsaidi** [comment]
Hi all!

Thanks for the lib - it's super useful! :)

I can have a look at the failing test and the changelog warning, so that the branch is ready to be merged into `master`, whenever you think switching over to Xcode 9 support is a good idea.

Until then, let me know if there's anything else I can do to help. I'll use the `swift4` branch of my from, but I guess you could pull that one in into a `swift4` branch of the official repo as well, if it looks ok.

**Comment by danielsaidi** [comment]
I have bumped Nimble in Cartfile and fixed some Xcode 9 compilation errors.

**Comment by ashfurrow** [comment]
Cool! I'll take a look and see if I can get CI passing.

**Comment by ashfurrow** [comment]
Okay! I've released this as version 6.3.0. As always, please let me know if you have any issues.

**Comment by danielsaidi** [comment]
Ah, great! Let me know if there's anything else I can do to help. I'll try to find time to look at some of the issues.

**Pull request merged**
