### PR TITLE
Add identifier to Snapshot

### PR DESCRIPTION
**Pull request by hfehrmann**
Hi!

This MR adds an identifier parameter to pretty syntax for `Snapshot`

I use this feature a lot and felt it was missing.

### CODE REVIEW

**Comment by dogo** [comment]
@hfehrmann thanks for your contribution, you also need to update the `PrettySyntax.swift`.

▸ Compiling PrettySyntax.swift
❌  /Users/distiller/Nimble-Snapshots/Nimble_Snapshots/PrettySyntax.swift:21:45: extra argument 'identifier' in call
    return Snapshot(name: name, identifier: identifier, record: false, usesDrawRect: usesDrawRect)

**Comment by hfehrmann** [comment]
@dogo Corrected! I couldn't actually compile the code so I made the modifications blind.

**Comment by dogo** [comment]
Great! Good job, LFTM @ashfurrow . Let's merge?

**Review by ashfurrow — APPROVED** [review]
Looks good! Sorry for the delay, I was offline. I'll get this released in a new version today.

**Comment by ashfurrow** [comment]
Alrigty, this was released as 9.1.0. Should be all set, thanks again!

**Pull request merged**
