### PR TITLE
Store the failed tests directory in the artifacts

### PR DESCRIPTION
**Pull request by Vkt0r**
• Set the `IMAGE_DIFF_DIR` ENV variable in the Bootstrap project for the failed tests directory
• Store the failed tests directory in the artifacts

I'm keeping `second_curtain` in the pipeline of `xcodebuild` but I think with this it doesn't make more sense to have it in the gems 🤔.

### CODE REVIEW

**Comment by Vkt0r** [comment]
@ashfurrow We should remove `second_curtain` or we keep for now ?. It doesn't hurt to have both options I think.

**Comment by ashfurrow** [comment]
I'm fine with removing second curtain tbh. CI artifacts are a much easier experience and don't require a whole AWS security dance 🕺 

It looks like things aren't be uploaded:

```
Uploading /Users/distiller/project/BootstrapTests/FailureDiffs to Users/distiller/project/BootstrapTests/FailureDiffs
  No artifact files found at /Users/distiller/project/BootstrapTests/FailureDiffs
```

**Comment by ashfurrow** [comment]
Cool cool!

**Comment by Vkt0r** [comment]
@ashfurrow Perfect, yes I already pushed a new change to fix that

**Comment by ashfurrow** [comment]
Do we need to `mkdir` it first maybe? Do the images get saved there when running locally?

**Comment by Vkt0r** [comment]
Yes, there are saved locally. I think it's a problem of permissions to create the dir in the CI. I'll try it to create the dir first.

**Comment by Vkt0r** [comment]
@ashfurrow  I was able to see what's the real problem here! `second_curtain` was working fine, even we don't need to create the `FailedDiffs` directory in the CI. I noticed the tests failing are not generating an output for the failure, this was making me crazy, so I decided to fail other tests intentionally to see the result in the CI and boom I got it if you see the result of this build you will see the result in the artifacts successfully.

Another weird thing is the `xcodebuild` log wasn't generating any output for `ksdiff`. I going to pass the tests again and see what's happening with that two test failing very intermittently and not generating any output in the failure.

**Comment by ashfurrow** [comment]
Hmm! Still failing – same tests. Maybe we should mark them as `pending` for now, and follow up later? https://circleci.com/gh/ashfurrow/Nimble-Snapshots/186

**Comment by Vkt0r** [comment]
Yes definitely 👍

**Pull request merged**
